<a href="https://colab.research.google.com/github/pablex72/deep-learning-ai/blob/main/python_numpy_vectors_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.random.rand(5)

In [3]:
print(a)

[0.99501389 0.13632716 0.51745381 0.86383917 0.19712402]


In [4]:
print(a.shape)

(5,)


In [5]:
print(a.T)

[0.99501389 0.13632716 0.51745381 0.86383917 0.19712402]


In [6]:
print(np.dot(a,a.T))

2.061472174785915


In [8]:
a = np.random.randn(5,1)
a

array([[ 0.20320337],
       [-0.19594955],
       [ 1.02009521],
       [-0.39483011],
       [ 0.63763831]])

In [9]:
a.T

array([[ 0.20320337, -0.19594955,  1.02009521, -0.39483011,  0.63763831]])

In [10]:
print(np.dot(a,a.T))

[[ 0.04129161 -0.03981761  0.20728678 -0.08023081  0.12957025]
 [-0.03981761  0.03839623 -0.1998872   0.07736678 -0.12494494]
 [ 0.20728678 -0.1998872   1.04059423 -0.4027643   0.65045179]
 [-0.08023081  0.07736678 -0.4027643   0.15589082 -0.25175881]
 [ 0.12957025 -0.12494494  0.65045179 -0.25175881  0.40658262]]
